CREATE TABLE `USER` (
	`USER_NO`	NUMBER	NOT NULL,
	`USER_ID`	VARCHAR2(20)	NOT NULL,
	`USER_PWD`	VARCHAR2(50)	NOT NULL,
	`USER_NAME`	VARCHAR2(20)	NOT NULL,
	`USER_NICK`	VARCHAR2(50)	NOT NULL,
	`USER_PHONE`	VARCHAR2(20)	NOT NULL,
	`USER_ADDRESS`	VARCHAR2(200)	NOT NULL,
	`USER_EMAIL`	VARCHAR2(30)	NOT NULL,
	`USER_POINT`	NUMBER	NULL	DEFAULT 0,
	`USER_ROLE`	VARCHAR2(10)	NOT NULL	DEFAULT 일반	COMMENT '판매자/관리자/일반',
	`USER_STATUS`	VARCHAR2(1)	NOT NULL	DEFAULT Y,
	`USER_REPORT`	NUMBER	NULL	DEFAULT 0
);

CREATE TABLE `PRODUCT` (
	`PRO_NO`	NUMBER	NOT NULL,
	`USER_NO`	NUMBER	NOT NULL,
	`PRO_,NAME`	VARCHAR2(100)	NOT NULL,
	`PRO_CONTENT`	VARCHAR2(4000)	NOT NULL,
	`PRO_IMG`	VARCHAR2(1000)	NOT NULL,
	`PRO_PRICE`	NUMBER	NOT NULL,
	`PRO_QUANTITY`	NUMBER	NOT NULL	DEFAULT 1,
	`PRO_DATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`PRO_STATUS`	VARCHAR2(1)	NOT NULL	DEFAULT Y,
	`PRO_REPORT`	NUMBER	NOT NULL	DEFAULT 0
);

CREATE TABLE `REVIEW` (
	`Key`	VARCHAR(255)	NOT NULL,
	`PRO_NO`	NUMBER	NULL,
	`BOARD_NO`	NUMBER	NULL,
	`USER_NO`	NUMBER	NOT NULL,
	`REVIEW_TITLE`	VARCHAR2(100)	NOT NULL,
	`REVIEW_WRITER`	VARCHAR2(20)	NOT NULL,
	`REVIEW_CONTENT`	VARCHAR2(4000)	NOT NULL,
	`REVIEW_IMG`	VARCHAR2(1000)	NULL,
	`REVIEW_DATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`REVIEW_SCORE`	NUMBER	NOT NULL	DEFAULT 0	COMMENT '1 ~ 5',
	`REVIEW_RECOMMEND`	NUMBER	NOT NULL	DEFAULT 0,
	`REVIEW_TYPE`	VARCHAR2(20)	NOT NULL	COMMENT '어디가지 & 상품',
	`REVIEW_STATUS`	VARCHAR2(1)	NOT NULL	DEFAULT Y,
	`REVIEW_REPORT`	NUMBER	NULL	DEFAULT 0
);

CREATE TABLE `CART` (
	`PRO_NO`	NUMBER	NOT NULL,
	`USER_NO`	NUMBER	NOT NULL
);

CREATE TABLE `BOARD` (
	`BOARD_NO`	NUMBER	NOT NULL,
	`USER_NO`	NUMBER	NOT NULL,
	`BOARD_WRITER`	VARCHAR2(20)	NOT NULL,
	`BOARD_CATEGORY`	VARCHAR2(20)	NULL	COMMENT '잡담 / 질문 / 숙소 / 맛집 / 병원 / 펫시터 /.. 등등',
	`BOARD_TITLE`	VARCHAR2(100)	NOT NULL,
	`BOARD_CONTENT`	VARCHAR2(4000)	NOT NULL,
	`BOARD_IMG`	VARCHAR2(1000)	NULL,
	`BOARD_DATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`BOARD_VIEWS`	NUMBER	NOT NULL	DEFAULT 0,
	`BOARD_STATUS`	VARCHAR2(1)	NOT NULL	DEFAULT Y,
	`BOARD_TYPE`	VARCHAR2(20)	NOT NULL	COMMENT '커뮤니티 / 공지사항/ 어디가지? / 펫시터',
	`BOARD_RECOMMEND`	NUMBER	NULL	DEFAULT 0,
	`BOARD_LOCATION`	VARCHAR2(1000)	NULL,
	`BOARD_REPORT`	NUMBER	NULL	DEFAULT 0
);

CREATE TABLE `LIKE` (
	`LIKE_NO`	NUMBER	NOT NULL,
	`USER_NO`	NUMBER	NOT NULL,
	`BOARD_NO`	NUMBER	NOT NULL
);

CREATE TABLE `PET` (
	`PET_NO`	NUMBER	NOT NULL,
	`USER_NO`	NUMBER	NOT NULL,
	`PET_NAME`	VARCHAR2(20)	NOT NULL,
	`PET_INFO`	VARCHAR2(1000)	NULL,
	`PET_TYPE`	VARCHAR2(1)	NOT NULL	COMMENT '강아지/고양이',
	`PET_WEIGHT`	NUMBER	NULL,
	`PET_STATUS`	VARCHAR2(1)	NOT NULL	DEFAULT Y
);

CREATE TABLE `PURCHASE` (
	`PUR_NO`	VARCHAR(20)	NOT NULL,
	`USER_NO`	NUMBER	NOT NULL,
	`ORDER_NO`	NUMBER	NOT NULL,
	`PUR_METHODS`	VARCHAR(20)	NOT NULL,
	`PUR_DATE`	DATE	NOT NULL,
	`PUR_FINAL_PRICE`	NUMBER	NOT NULL,
	`PUR_ADD_PRICE`	NUMBER	NULL,
	`PUR_PRICE`	NUMBER	NULL,
	`PUR_NAME`	VARCHAR(20)	NULL,
	`PUR_BANK`	VARCHAR(20)	NULL
);

CREATE TABLE `ORDER` (
	`ORDER_NO`	NUMBER	NOT NULL,
	`PRO_NO`	NUMBER	NOT NULL,
	`USER_NO`	NUMBER	NOT NULL,
	`ORDER_DATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`ORDER_STATUS`	VARCHAR2(20)	NOT NULL	DEFAULT 상품 준비중	COMMENT '상품 준비중 & 배송준비중  & 배송보류 & 배송대기 & 배송중 & 배송 완료',
	`PUR_STATUS`	VARCHAR2(20)	NOT NULL	DEFAULT 입금 전	COMMENT '입금 전 & 입금대기 & 입금완료(수동) & 입금완료(자동) & 결제완료',
	`CS_STATUS`	VARCHAR2(20)	NULL	COMMENT '상품취소 & 교환 & 반품 & 환불',
	`PRO_PRICE`	NUMBER	NOT NULL	COMMENT '판매가 * 상품 수량',
	`PRO_POINT`	NUMBER	NULL,
	`DELIVERY_FEE`	NUMBER	NOT NULL	DEFAULT 3000
);

CREATE TABLE `REPORT` (
	`REPORT_NO`	NUMBER	NOT NULL,
	`USER_NO`	NUMBER	NOT NULL,
	`REPORT_TYPE`	VARCHAR2(20)	NOT NULL	COMMENT '스팸/음란물/불법/유해/욕설/기타',
	`REPORT_CONTENT`	VARCHAR2(4000)	NULL,
	`REPORT_DATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`TARGET_USER`	NUMBER	NOT NULL	COMMENT '신고를 당한 회원, 즉 신고당한 게시물이나 댓글을 쓴 회원의 PK',
	`TARGET_KEY`	NUMBER	NOT NULL	COMMENT '신고한 게시물이나 리뷰의 PK',
	`TARGET_TYPE`	NUMBER	NOT NULL	COMMENT '커뮤니티 게시글(1)/ 커뮤티니 댓글(2) /어디가지 리뷰 (3) / 상품 (4) / 상품리뷰(5)'
);

CREATE TABLE `POINT` (
	`POINT_NO`	NUMBER	NOT NULL,
	`USER_NO`	NUMBER	NOT NULL,
	`POINT_ROUTE`	VARCHER2(1000)	NULL,
	`POINT_DATE`	DATE	NOT NULL	DEFAULT SYSDATE,
	`POINT_IN_OUT`	VARCHER2(5)	NULL	COMMENT 'PLUS / MINUS( + / - )',
	`PONT_CUR`	NUMBER	NOT NULL	DEFAULT 0
);

CREATE TABLE `SELLER` (
	`SELLER_NO`	NUMBER	NOT NULL,
	`SHOP_NAME`	VARCHAR2(50)	NOT NULL,
	`SHOP_LICENSE`	NUMBER	NOT NULL
);

CREATE TABLE `FOOD` (
	`FOOD_NO`	NUMBER	NOT NULL,
	`FOOD_NAME`	VARCHAR2(20)	NOT NULL,
	`FOOD_CONTENT`	VARCHAR2(1000)	NOT NULL,
	`FOOD_IMG`	VARCHAR2(1000)	NULL,
	`PET_TYPE`	VARCHAR2(1)	NOT NULL	COMMENT '강아지 / 고양이 / 기타',
	`FOOD_OR`	VARCHAR2(1)	NOT NULL	COMMENT 'O / X'
);

CREATE TABLE `REPLY` (
	`REPLY_NO`	NUMBER	NOT NULL	COMMENT '댓글번호',
	`BOARD_NO`	NUMBER	NOT NULL	COMMENT '댓글이작성된게시글',
	`USER_NO`	NUMBER	NOT NULL	COMMENT '댓글작성자',
	`REPLY_CONTENT`	VARCHAR2(2000)	NOT NULL	COMMENT '댓글내용',
	`REPLY_STATUS`	VARCHAR2(1)	NOT NULL	DEFAULT Y	COMMENT '상태값(Y/N)',
	`REPLY_CREATE_DATE`	DATE	NOT NULL	DEFAULT SYSDATE	COMMENT '댓글올린날짜',
	`REPLY_MODIFY_DATE`	DATE	NOT NULL	COMMENT '댓글수정날짜',
	`REPLY_REPORT`	NUMBER	NULL	DEFAULT 0
);

CREATE TABLE `CALENDAR` (
	`CAL_NO`	NUMBER	NOT NULL,
	`USER_NO`	NUMBER	NOT NULL,
	`CAL_TITLE`	VARCHAR2(100)	NOT NULL,
	`CAL_CONTENT`	VARCHAR2(1000)	NOT NULL,
	`CAL_DATE`	DATE	NOT NULL	DEFAULT SYSDATE
);

ALTER TABLE `USER` ADD CONSTRAINT `PK_USER` PRIMARY KEY (
	`USER_NO`
);

ALTER TABLE `PRODUCT` ADD CONSTRAINT `PK_PRODUCT` PRIMARY KEY (
	`PRO_NO`
);

ALTER TABLE `REVIEW` ADD CONSTRAINT `PK_REVIEW` PRIMARY KEY (
	`Key`
);

ALTER TABLE `BOARD` ADD CONSTRAINT `PK_BOARD` PRIMARY KEY (
	`BOARD_NO`
);

ALTER TABLE `LIKE` ADD CONSTRAINT `PK_LIKE` PRIMARY KEY (
	`LIKE_NO`
);

ALTER TABLE `PET` ADD CONSTRAINT `PK_PET` PRIMARY KEY (
	`PET_NO`
);

ALTER TABLE `PURCHASE` ADD CONSTRAINT `PK_PURCHASE` PRIMARY KEY (
	`PUR_NO`
);

ALTER TABLE `ORDER` ADD CONSTRAINT `PK_ORDER` PRIMARY KEY (
	`ORDER_NO`
);

ALTER TABLE `REPORT` ADD CONSTRAINT `PK_REPORT` PRIMARY KEY (
	`REPORT_NO`
);

ALTER TABLE `POINT` ADD CONSTRAINT `PK_POINT` PRIMARY KEY (
	`POINT_NO`
);

ALTER TABLE `SELLER` ADD CONSTRAINT `PK_SELLER` PRIMARY KEY (
	`SELLER_NO`
);

ALTER TABLE `FOOD` ADD CONSTRAINT `PK_FOOD` PRIMARY KEY (
	`FOOD_NO`
);

ALTER TABLE `REPLY` ADD CONSTRAINT `PK_REPLY` PRIMARY KEY (
	`REPLY_NO`
);

ALTER TABLE `CALENDAR` ADD CONSTRAINT `PK_CALENDAR` PRIMARY KEY (
	`CAL_NO`
);

ALTER TABLE `SELLER` ADD CONSTRAINT `FK_USER_TO_SELLER_1` FOREIGN KEY (
	`SELLER_NO`
)
REFERENCES `USER` (
	`USER_NO`
);

